/*
 * MATLAB Compiler: 4.2 (R14SP2)
 * Date: Tue Jan 24 14:33:12 2006
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "imager"
 * "-a" "imager_activex23" "-a" "imager_activex24" "-a" "imager_activex25" "-a"
 * "imager_activex26" "-a" "imager_activex27" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_imager_public_data[] = {'3', '0', '8', '1', '9',
                                                  'D', '3', '0', '0', 'D',
                                                  '0', '6', '0', '9', '2',
                                                  'A', '8', '6', '4', '8',
                                                  '8', '6', 'F', '7', '0',
                                                  'D', '0', '1', '0', '1',
                                                  '0', '1', '0', '5', '0',
                                                  '0', '0', '3', '8', '1',
                                                  '8', 'B', '0', '0', '3',
                                                  '0', '8', '1', '8', '7',
                                                  '0', '2', '8', '1', '8',
                                                  '1', '0', '0', 'C', '4',
                                                  '9', 'C', 'A', 'C', '3',
                                                  '4', 'E', 'D', '1', '3',
                                                  'A', '5', '2', '0', '6',
                                                  '5', '8', 'F', '6', 'F',
                                                  '8', 'E', '0', '1', '3',
                                                  '8', 'C', '4', '3', '1',
                                                  '5', 'B', '4', '3', '1',
                                                  '5', '2', '7', '7', 'E',
                                                  'D', '3', 'F', '7', 'D',
                                                  'A', 'E', '5', '3', '0',
                                                  '9', '9', 'D', 'B', '0',
                                                  '8', 'E', 'E', '5', '8',
                                                  '9', 'F', '8', '0', '4',
                                                  'D', '4', 'B', '9', '8',
                                                  '1', '3', '2', '6', 'A',
                                                  '5', '2', 'C', 'C', 'E',
                                                  '4', '3', '8', '2', 'E',
                                                  '9', 'F', '2', 'B', '4',
                                                  'D', '0', '8', '5', 'E',
                                                  'B', '9', '5', '0', 'C',
                                                  '7', 'A', 'B', '1', '2',
                                                  'E', 'D', 'E', '2', 'D',
                                                  '4', '1', '2', '9', '7',
                                                  '8', '2', '0', 'E', '6',
                                                  '3', '7', '7', 'A', '5',
                                                  'F', 'E', 'B', '5', '6',
                                                  '8', '9', 'D', '4', 'E',
                                                  '6', '0', '3', '2', 'F',
                                                  '6', '0', 'C', '4', '3',
                                                  '0', '7', '4', 'A', '0',
                                                  '4', 'C', '2', '6', 'A',
                                                  'B', '7', '2', 'F', '5',
                                                  '4', 'B', '5', '1', 'B',
                                                  'B', '4', '6', '0', '5',
                                                  '7', '8', '7', '8', '5',
                                                  'B', '1', '9', '9', '0',
                                                  '1', '4', '3', '1', '4',
                                                  'A', '6', '5', 'F', '0',
                                                  '9', '0', 'B', '6', '1',
                                                  'F', 'C', '2', '0', '1',
                                                  '6', '9', '4', '5', '3',
                                                  'B', '5', '8', 'F', 'C',
                                                  '8', 'B', 'A', '4', '3',
                                                  'E', '6', '7', '7', '6',
                                                  'E', 'B', '7', 'E', 'C',
                                                  'D', '3', '1', '7', '8',
                                                  'B', '5', '6', 'A', 'B',
                                                  '0', 'F', 'A', '0', '6',
                                                  'D', 'D', '6', '4', '9',
                                                  '6', '7', 'C', 'B', '1',
                                                  '4', '9', 'E', '5', '0',
                                                  '2', '0', '1', '1', '1'
                                                  , '\0'};

const char *__MCC_imager_name_data = "imager";

const char *__MCC_imager_root_data = "";

const unsigned char __MCC_imager_session_data[] = {'3', '5', 'E', '3', 'C',
                                                   '5', 'A', 'A', '8', 'A',
                                                   'B', 'B', '7', 'A', '8',
                                                   '6', 'A', '1', 'E', '8',
                                                   '3', '3', '4', 'E', '7',
                                                   'E', 'F', '0', 'B', 'B',
                                                   '3', '0', '3', '3', '8',
                                                   '8', '1', 'B', 'D', '0',
                                                   'A', '3', 'A', '3', '7',
                                                   'B', 'B', '7', '9', 'C',
                                                   '4', '9', '3', '0', '5',
                                                   'E', '9', 'C', 'E', '6',
                                                   'B', '2', '8', 'A', '5',
                                                   '9', '1', 'F', '7', '0',
                                                   '8', 'C', 'F', 'B', 'B',
                                                   '0', 'F', '1', 'B', 'B',
                                                   '2', '8', 'D', '8', '6',
                                                   '4', 'F', '1', '0', '7',
                                                   '5', 'C', '1', '5', '2',
                                                   'A', '3', '9', '2', 'F',
                                                   'D', '9', 'A', '0', 'E',
                                                   'A', '4', '9', '4', '0',
                                                   'E', '3', '7', '6', '8',
                                                   '9', '8', '4', '5', '1',
                                                   '9', '0', 'C', '4', '7',
                                                   'C', '1', '4', '5', '3',
                                                   '1', 'F', '3', 'B', 'D',
                                                   '9', 'E', '5', '7', 'F',
                                                   '7', 'F', '4', '2', 'B',
                                                   '9', '8', 'E', '4', '5',
                                                   '3', '6', '9', 'B', 'B',
                                                   '4', 'D', '2', 'B', 'E',
                                                   '0', '9', '1', 'E', 'D',
                                                   '7', '4', '5', '0', '7',
                                                   'C', 'F', 'F', '2', 'C',
                                                   '9', 'D', '9', '9', 'F',
                                                   '7', '0', '9', 'C', '5',
                                                   'D', '1', '7', '8', '6',
                                                   '2', '3', 'B', '0', '3',
                                                   'D', 'F', 'A', 'F', '8',
                                                   '3', '2', '1', 'C', '1',
                                                   '6', '6', '8', '7', '8',
                                                   '3', 'C', 'C', '4', '0',
                                                   '3', 'B', 'C', '2', '7',
                                                   'A', '7', '7', '3', 'D',
                                                   'F', 'B', '5', 'A', '4',
                                                   'F', '7', '8', '7', '0',
                                                   '6', 'C', '4', '8', '7',
                                                   '1', '4', '8', 'A', '3',
                                                   '7', '5', '9', 'D', '6',
                                                   '2', '3', '1', '1', '3',
                                                   'E', '\0'};

const char *__MCC_imager_matlabpath_data[] = {"imager/",
                                              "toolbox/compiler/deploy/",
                                              "neurostuff/neurodata/dario/cbpep/",
                                              "neurostuff/neurodata/dario/pep2matlab_new/",
                                              "neurostuff/neurodata/dario/pepanalysis/",
                                              "neurostuff/neurodata/dario/matlab5/",
                                              "neurostuff/neurodata/dario/sortnev_dario_2/",
                                              "neurostuff/neurodata/dario/simul/",
                                              "$TOOLBOXMATLABDIR/general/",
                                              "$TOOLBOXMATLABDIR/ops/",
                                              "$TOOLBOXMATLABDIR/lang/",
                                              "$TOOLBOXMATLABDIR/elmat/",
                                              "$TOOLBOXMATLABDIR/elfun/",
                                              "$TOOLBOXMATLABDIR/specfun/",
                                              "$TOOLBOXMATLABDIR/matfun/",
                                              "$TOOLBOXMATLABDIR/datafun/",
                                              "$TOOLBOXMATLABDIR/polyfun/",
                                              "$TOOLBOXMATLABDIR/funfun/",
                                              "$TOOLBOXMATLABDIR/sparfun/",
                                              "$TOOLBOXMATLABDIR/scribe/",
                                              "$TOOLBOXMATLABDIR/graph2d/",
                                              "$TOOLBOXMATLABDIR/graph3d/",
                                              "$TOOLBOXMATLABDIR/specgraph/",
                                              "$TOOLBOXMATLABDIR/graphics/",
                                              "$TOOLBOXMATLABDIR/uitools/",
                                              "$TOOLBOXMATLABDIR/strfun/",
                                              "$TOOLBOXMATLABDIR/imagesci/",
                                              "$TOOLBOXMATLABDIR/iofun/",
                                              "$TOOLBOXMATLABDIR/audiovideo/",
                                              "$TOOLBOXMATLABDIR/timefun/",
                                              "$TOOLBOXMATLABDIR/datatypes/",
                                              "$TOOLBOXMATLABDIR/verctrl/",
                                              "$TOOLBOXMATLABDIR/codetools/",
                                              "$TOOLBOXMATLABDIR/helptools/",
                                              "$TOOLBOXMATLABDIR/winfun/",
                                              "$TOOLBOXMATLABDIR/demos/",
                                              "$TOOLBOXMATLABDIR/timeseries/",
                                              "$TOOLBOXMATLABDIR/hds/",
                                              "toolbox/local/",
                                              "toolbox/shared/controllib/",
                                              "toolbox/compiler/",
                                              "toolbox/control/control/",
                                              "toolbox/control/ctrlguis/",
                                              "toolbox/control/ctrlobsolete/",
                                              "toolbox/control/ctrlutil/",
                                              "toolbox/images/images/",
                                              "toolbox/images/imuitools/",
                                              "toolbox/instrument/instrument/",
                                              "toolbox/nnet/nnet/",
                                              "toolbox/nnet/nnutils/",
                                              "toolbox/optim/",
                                              "toolbox/signal/signal/",
                                              "toolbox/signal/sigtools/",
                                              "toolbox/stats/"};
const int __MCC_imager_matlabpath_data_count = 54;

const char *__MCC_imager_classpath_data[] = {"java/jar/toolbox/control.jar",
                                             "java/jar/toolbox/instrument.jar",
                                             "java/jar/toolbox/testmeas.jar"};
const int __MCC_imager_classpath_data_count = 3;

const char *__MCC_imager_lib_path_data[] = {"bin/win32/"};
const int __MCC_imager_lib_path_data_count = 1;

const char *__MCC_imager_mcr_application_options[] = { "" };
const int __MCC_imager_mcr_application_option_count = 0;
const char *__MCC_imager_mcr_runtime_options[] = { "" };
const int __MCC_imager_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


